const nodes = await framer.agent.serializeNodes({
    ids: [
        "WQLkyLRf1",
        "t62LHpSTa",
        "u75vHQkAR",
        "yAd2lMDSW",
        "t62LHpSTayAd2lMDSW",
        "u75vHQkARyAd2lMDSW",
        "OdvHkNWXz",
        "omF0gODuR",
        "augiA20Il",
        "eT5aUzOXW",
        "pTPGQ4L6O",
        "FZFYEKdG1",
        "GPILtKFJP",
        "S4aeyJLQa",
        "S4aeyJLQaebjghUxzc",
        "JN7M7ldcs",
        "O2btPltNw",
        "aIET_2yab",
    ],
    depth: 4,
    attributeFilter: [
        "name",
        "layoutTemplate",
        "$layoutTemplateId",
        "fill",
        "width",
        "height",
        "collectionList",
        "text",
        "textContent",
        "$control__variant",
        "overflow",
        "layout",
        "padding",
        "gap",
        "visible",
    ],
})

console.log(JSON.stringify(nodes, null, 2))
