const controls = await framer.agent.readComponentControls({
    componentIds: ["OdvHkNWXz", "IhgjBMpmC"],
})

const tree = await framer.agent.serializeNodes({
    ids: [
        "augiA20Il",
        "FZFYEKdG1",
        "eT5aUzOXW",
        "pTPGQ4L6O",
        "GPILtKFJP",
        "IhgjBMpmC",
        "GiR6fF7o5",
        "Nx5jccWgM",
        "tKUMOkWpP",
        "yZes1fNVs",
        "eGJAoz6x_",
        "S4aeyJLQaebjghUxzc",
        "pWw0UM2JG",
        "BU8_2gg2U",
        "axW_NfbLI",
        "odgkshwbV",
        "oSHXrizqB",
        "FnQbHIoGD",
        "DZIMTQiKB",
        "QhfNwiny9",
        "omF0gODuR",
        "NoEH4ZcYo",
        "iXNR1Kgi9",
    ],
    depth: 2,
    attributeFilter: [
        "name",
        "path",
        "layoutTemplate",
        "$layoutTemplateId",
        "left",
        "top",
        "width",
        "height",
        "overflow",
        "hideScrollbars",
        "stackDirection",
        "gap",
        "padding",
        "fill",
        "text",
        "textStylePreset",
        "link",
        "collectionList",
    ],
})

console.log(JSON.stringify({ controls, tree }, null, 2))
